import { Employee } from "@/api/types.ts";

export const fetchEmployees = (): Employee[] => {
  return [
    {
      id: "1",
      name: "John",
      surname: "Doe",
      age: 34,
      position: "Aerospace Engineer",
      orgId: "9",
    },
    {
      id: "2",
      name: "Alice",
      surname: "Smith",
      age: 29,
      position: "Project Manager",
      orgId: "9",
    },
    {
      id: "3",
      name: "Michael",
      surname: "Brown",
      age: 41,
      position: "Chief Scientist",
      orgId: "9",
    },
    {
      id: "1",
      name: "Emma",
      surname: "Johnson",
      age: 27,
      position: "AI Researcher",
      orgId: "10",
    },
    {
      id: "2",
      name: "Liam",
      surname: "Williams",
      age: 32,
      position: "Software Engineer",
      orgId: "10",
    },
    {
      id: "3",
      name: "Olivia",
      surname: "Jones",
      age: 30,
      position: "Data Analyst",
      orgId: "10",
    },
    {
      id: "1",
      name: "Sophia",
      surname: "Taylor",
      age: 36,
      position: "Mechanical Engineer",
      orgId: "11",
    },
    {
      id: "2",
      name: "Ethan",
      surname: "Martinez",
      age: 38,
      position: "Operations Manager",
      orgId: "11",
    },
    {
      id: "3",
      name: "Mason",
      surname: "Garcia",
      age: 33,
      position: "Environmental Specialist",
      orgId: "11",
    },
    {
      id: "1",
      name: "Isabella",
      surname: "Clark",
      age: 31,
      position: "Neural Engineer",
      orgId: "12",
    },
    {
      id: "2",
      name: "James",
      surname: "Moore",
      age: 29,
      position: "Systems Architect",
      orgId: "12",
    },
    {
      id: "3",
      name: "Charlotte",
      surname: "Walker",
      age: 35,
      position: "Human-Computer Interaction Specialist",
      orgId: "12",
    },
    {
      id: "1",
      name: "Ava",
      surname: "Hall",
      age: 40,
      position: "Energy Consultant",
      orgId: "13",
    },
    {
      id: "2",
      name: "Lucas",
      surname: "Adams",
      age: 28,
      position: "Power Systems Analyst",
      orgId: "13",
    },
    {
      id: "3",
      name: "Mia",
      surname: "Turner",
      age: 37,
      position: "Smart Grid Specialist",
      orgId: "13",
    },
  ];
};
